BaseURL = "http://xiaohaoppy.daoapp.io/"
LanguageCode = "zh-CN"
HasCJKLanguage = true
Title = "风海啸博客"
Theme = "hugo-pacman-theme"
pygmentsStyle = "default"
pygmentsUseClasses = true
RSSUri = "feed.xml"

[Author]
  Name = "风海啸"

[Params]
  AuthorHomepage = "http://xiaohaoppy.daoapp.io/"
  BottomIntroduce = "Introduce1 <br/> Introduce2"
  Description = ""
  Subtitle = "莫问前路为何出，飘然一身在风中。"
  #Weibo = "coderzh"
  #WeiboID = 1816308191
  #Twitter = "coderzh"
  #GitHub = "coderzh"
  #Facebook = "coderzh"
  #LinkIn = "coderzh"
  Imglogo = "img/logo.svg"
  AuthorImg = "img/author.jpg"
  DateFormat = "2006年01月02日"
  MonthFormat = "2006年01月"
  FancyBox = true

  #[Params.DuoShuo]
  #  ShortName = "coderzh"

  #[Params.Disqus]
  #  ShortName = "coderzh"

  [Params.GoogleAnalytics]
    ID = "UA-76508926-1"

  [Params.Strings]
    Search = "搜索"
    PageNotFound = "你访问的页面不存在"
    ShowSideBar = "显示侧边栏"
    HideSideBar = "隐藏侧边栏"
    Categories = "分类"
    Archive = "归档"
    Tags = "标签"
    TagCloud = "标签云"
    Rss = "RSS 订阅"
    TableOfContents = "文章目录"

[Menu]
  [[Menu.Main]]
    Name = "首页"
    URL = "/"
    Weight = 1
  [[Menu.Main]]
    Name = "关于"
    URL = "/about"
    Weight = 2
